version: 2.1

executors:
  docker-exec:
    docker:
      - image: docker:17.05.0-ce-git
jobs:
  build_and_deploy:
    executor: docker-exec
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          command: |
            docker build -t man .
            echo "this is the deploy step"
            docker run -p 4001:4001 man

  # deploy:
  #   executor: docker-exec
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           echo "this is the deploy step"

workflow:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: main
